In [1]:
import numpy as np
import pinocchio as pin

In [2]:
%%capture
!pip3 install robot_descriptions
from robot_descriptions import (
    z1_mj_description,
    z1_description,
    skydio_x2_mj_description,
    skydio_x2_description,
)

In [3]:
ROBOT_URDF = skydio_x2_description.URDF_PATH
ROBOT_XML = skydio_x2_mj_description.MJCF_PATH

ROBOT_URDF = z1_description.URDF_PATH
ROBOT_XML = z1_mj_description.MJCF_PATH

In [4]:
pin_model = pin.buildModelFromUrdf(ROBOT_URDF)
pin_data = pin_model.createData()

In [5]:
q = np.random.randn(pin_model.nq)
dq = np.random.randn(pin_model.nv)
ddq = np.random.randn(pin_model.nv)
# q[:3] = np.zeros(3)
# dq[:3] = np.zeros(3)
# ddq[:3] = np.zeros(3)

if pin_model.nq != pin_model.nv:
    q[3:7] /= np.linalg.norm(q[3:7])
    
pin_data.q = q.copy()
pin_data.dq = dq.copy()
pin_data.ddq = ddq.copy()

### Regressor in Mujoco

In [6]:
import mujoco

In [7]:
0# Load model, make data
mj_model = mujoco.MjModel.from_xml_path(ROBOT_XML)
mj_data = mujoco.MjData(mj_model)
mj_model.opt.enableflags |= mujoco.mjtEnableBit.mjENBL_ENERGY
body_offset = np.where(mj_model.body_dofadr == 0)[0][0]
# model.energy.setflags(enable=True)

# Set the state to the "squat" keyframe, call mj_forward.
# key = model.key('hover').id
# mujoco.mj_resetDataKeyframe(model, data, key)

q_muj = q.copy()
dq_muj = dq.copy()
ddq_muj = ddq.copy()

if mj_model.nq != mj_model.nv:
    q_muj[[3, 4, 5, 6]] = q[[6, 3, 4, 5]]
    mj_data.qpos = q_muj
    mujoco.mj_kinematics(mj_model, mj_data)
    rotation = mj_data.xmat[1].reshape(3, 3).copy()
    dq_muj[:3] = rotation@dq_muj[:3]
    ddq_muj[:3] = rotation@ddq_muj[:3]# + np.cross(dq_muj[:3], dq_muj[3:]))

mj_data.qpos = q_muj
mj_data.qvel = dq_muj
mj_data.qacc = ddq_muj 

In [8]:
mujoco.mj_inverse(mj_model, mj_data)

In [9]:
def Y_body(v_lin, v_ang, a_lin, a_ang):
    # this is identical to the pinnochio: pin.bodyRegressor(*[v_lin, v_ang], *[a_lin, a_ang])
    v1, v2, v3 = v_lin
    v4, v5, v6 = v_ang

    a1, a2, a3 = a_lin
    a4, a5, a6 = a_ang

    # fmt: off
    Y = np.array([
        [a1 - v2*v6 + v3*v5, -v5**2 - v6**2, -a6 + v4*v5, a5 + v4*v6, 0, 0, 0, 0, 0, 0],
        [a2 + v1*v6 - v3*v4, a6 + v4*v5, -v4**2 - v6**2, -a4 + v5*v6, 0, 0, 0, 0, 0, 0],
        [a3 - v1*v5 + v2*v4, -a5 + v4*v6, a4 + v5*v6, -v4**2 - v5**2, 0, 0, 0, 0, 0, 0],
        [0, 0, a3 - v1*v5 + v2*v4, -a2 - v1*v6 + v3*v4, a4, a5 - v4*v6, -v5*v6, a6 + v4*v5, v5**2 - v6**2, v5*v6],
        [0, -a3 + v1*v5 - v2*v4, 0, a1 - v2*v6 + v3*v5, v4*v6, a4 + v5*v6, a5, -v4**2 + v6**2, a6 - v4*v5, -v4*v6],
        [0, a2 + v1*v6 - v3*v4, -a1 + v2*v6 - v3*v5, 0, -v4*v5, v4**2 - v5**2, v4*v5, a4 - v5*v6, a5 + v4*v6, a6]
    ])
    # fmt: on

    return Y


def mj_bodyRegressor(mj_model, mj_data, body_id):
    # TODO:
    # Clarify more about transformations:
    # not working properly with floating joint
    # https://mujoco.readthedocs.io/en/stable/programming/simulation.html#coordinate-frames-and-transformations
    # https://royfeatherstone.org/teaching/index.html
    # https://royfeatherstone.org/teaching/2008/slides.pdf

    velocity = np.zeros(6)
    accel = np.zeros(6)
    _cross = np.zeros(3)

    mujoco.mj_objectVelocity(mj_model, mj_data, 2, body_id, velocity, 1)
    mujoco.mj_rnePostConstraint(mj_model, mj_data)
    mujoco.mj_objectAcceleration(mj_model, mj_data, 2, body_id, accel, 1)
    # rotation = mj_data.xmat[body_id].reshape(3, 3).copy()

    v, w = velocity[3:], velocity[:3]
    dv, dw = accel[3:], accel[:3]  # dv - classical acceleration, already containt g
    mujoco.mju_cross(_cross, w, v)
    
    # in floating body, should be canceled?
    dv -= _cross
    # print(v, w)
    # print(dv, dw)
    
    Y = Y_body(v, w, dv, dw)
    return Y


def mj_jointRegressor(mj_model, mj_data, body_offset = 0):
    # TODO:
    # Investigate spatial tranfromation mju_transformSpatial t
    # not working properly with floating joint
    
    njoints = mj_model.njnt
    body_regressors = np.zeros((6 * njoints, njoints * 10))
    col_jac = np.zeros((6 * njoints, mj_model.nv))
    jac_lin = np.zeros((3, mj_model.nv))
    jac_rot = np.zeros((3, mj_model.nv))

    for i in range(njoints):
        # calculate cody regressors
        body_regressors[6 * i : 6 * (i + 1), 10 * i : 10 * (i + 1)] = mj_bodyRegressor(
            mj_model, mj_data, i + body_offset
        )  
        
        mujoco.mj_jacBody(mj_model, mj_data, jac_lin, jac_rot, i + body_offset)


        # Calculate jacobians
        rotation = mj_data.xmat[i + body_offset].reshape(3, 3).copy()
        col_jac[6 * i : 6 * i + 3, :] = rotation.T @ jac_lin.copy()
        col_jac[6 * i + 3 : 6 * i + 6, :] = rotation.T @ jac_rot.copy()

    joint_regressor = col_jac.T @ body_regressors
    return joint_regressor


### Compare Joint regressors

In [10]:
joint_regressor_muj = mj_jointRegressor(mj_model, mj_data, body_offset=body_offset)

In [11]:
pin.computeAllTerms(pin_model, pin_data, q, dq)
pin.forwardKinematics(pin_model, pin_data, q, dq, ddq)
joint_regressor_pin = pin.computeJointTorqueRegressor(pin_model, pin_data, q, dq, ddq)

In [12]:
joint_regressor_muj

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.91848709e-03,  0.00000000e+00,  3.38406141e-19,
         3.63491515e-16, -1.24580716e-19, -8.37828294e-01,
        -2.07024949e+00,  1.55696383e-16, -1.96522709e+00,
        -2.84428720e-01,  8.43746781e-01,  1.03358981e-01,
        -1.16936178e+00, -7.24587320e-01, -5.45093721e-01,
        -1.86150361e+00, -3.19354321e+00,  1.42206762e-16,
         7.71620645e-01,  2.55455943e+00,  1.86742210e+00,
        -1.09521044e-01,  3.64471886e-01, -1.74004787e-01,
         9.50458047e-01, -1.91298451e+00,  3.52911727e+00,
        -2.53619978e-17,  4.30258591e-01, -2.34283865e+00,
         1.91890300e+00, -7.46053875e-02,  6.78717410e-01,
        -2.82849366e-01,  9.20339945e-01, -3.67026607e+00,
        -1.22726023e+00,  1.75728156e+00,  1.03038854e+00,
        -2.32128094e+00,  1.70608531e-01, -3.65457630e-0

In [13]:
np.allclose(joint_regressor_muj, joint_regressor_pin)

True

In [14]:
joint_regressor_pin

array([[ 0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
         0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.91848709e-03,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -8.37828294e-01,
        -2.07024949e+00,  0.00000000e+00, -1.96522709e+00,
        -2.84428720e-01,  8.43746781e-01,  1.03358981e-01,
        -1.16936178e+00, -7.24587320e-01, -5.45093721e-01,
        -1.86150361e+00, -3.19354321e+00,  1.11022302e-16,
         7.71620645e-01,  2.55455943e+00,  1.86742210e+00,
        -1.09521044e-01,  3.64471886e-01, -1.74004787e-01,
         9.50458047e-01, -1.91298451e+00,  3.52911727e+00,
        -2.22044605e-16,  4.30258591e-01, -2.34283865e+00,
         1.91890300e+00, -7.46053875e-02,  6.78717410e-01,
        -2.82849366e-01,  9.20339945e-01, -3.67026607e+00,
        -1.22726023e+00,  1.75728156e+00,  1.03038854e+00,
        -2.32128094e+00,  1.70608531e-01, -3.65457630e-0

### Compare Body regressors

In [22]:
body_id = 3

In [23]:
body_regressor_muj = mj_bodyRegressor(mj_model, mj_data, body_id)

In [24]:
v_spatial = pin.getVelocity(pin_model, pin_data, body_id, pin.LOCAL)
a_spatial = np.array(pin.getAcceleration(pin_model, pin_data, body_id, pin.LOCAL))
rotation = pin_data.oMi[body_id].rotation
a_spatial[:3] -= rotation.T @ pin_model.gravity.linear
print(v_spatial, a_spatial)

  v =  0.241902 -0.312755  0.409191
  w = 0.737923  1.99951 0.601813
 [ 7.16493979 -0.15831549  6.05931523 -1.19874515 -0.86033441  1.47922537]


In [25]:
body_regressor_pin = pin.bodyRegressor(pin.Motion(v_spatial), pin.Motion(a_spatial))

In [26]:
mj_model.nbody

8

In [27]:
body_regressor_pin

array([[ 8.17134051e+00, -4.36021847e+00, -3.74057454e-03,
        -4.16242296e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-3.14687047e-01,  2.95471016e+00, -9.06710135e-01,
         2.40207687e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 5.34484113e+00,  1.30442653e+00,  4.58656642e-03,
        -4.54256990e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  5.34484113e+00,
         3.14687047e-01, -1.19874515e+00, -1.30442653e+00,
        -1.20333172e+00,  2.95471016e+00,  3.63585977e+00,
         1.20333172e+00],
       [ 0.00000000e+00, -5.34484113e+00,  0.00000000e+00,
         8.17134051e+00,  4.44092115e-01,  4.58656642e-03,
        -8.60334410e-01, -1.82351430e-01,  3.74057454e-03,
        -4.

In [28]:
np.allclose(body_regressor_muj, body_regressor_pin)

False